name: testflutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  path_provider: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3

dev_dependencies:
  sqflite_common_ffi: ^2.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/